StockExchange/Models/ErrorViewModel.cs
using System;

namespace StockExchange.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

StockExchange/Controllers/BaseController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Configuration;
using StockExchange.Services.Implementations;

namespace StockExchange.Controllers
{
    public class BaseController : Controller
    {
        protected CountryService countryService;
        protected CurrencyService currencyService;
        public BaseController(IConfiguration configuration)
        {
            countryService = new CountryService(configuration.GetConnectionString("JsonBD"));
            currencyService = new CurrencyService(configuration.GetConnectionString("JsonBD"));
        }
    }
}

StockExchange/Controllers/CountriesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.Extensions.Configuration;

namespace StockExchange.Controllers
{
    public class CountriesController : BaseController
    {
  
        public CountriesController(IConfiguration configuration) : base(configuration)
        {
        }

        // GET: Countries
        public async Task<IActionResult> Index()
        {
            return base.View(
                await countryService.GetCountriesAsync()
                );
        }



        // GET: Countries/Details/5
        /*
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var countries = await client.GetCountryCurrencies();

            if (countries == null)
            {
                return NotFound();
            }

            return View(countries.FirstOrDefault(c => c.CountryId == id));
        }*/
    

    }
}

StockExchange/Controllers/CurrenciesController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Configuration;
using System.Threading.Tasks;

namespace StockExchange.Controllers
{
    public class CurrenciesController : BaseController
    {
        public CurrenciesController(IConfiguration configuration) : base(configuration)
        {
        }

        // GET: Countries
        public async Task<IActionResult> Index()
        {
            return base.View(
                await currencyService.GetCurrenciesAsync()
                );
        }
    }
}

StockExchange/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using StockExchange.Models;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;

namespace StockExchange.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

StockExchange/Views/Countries/Details.cshtml
@model StockExchangeLib.Models.Country

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>Country</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Name)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Currencies)
        </dt>
        <dd class = "col-sm-10">
            @*@Html.DisplayFor(model => model.CurrencyType)*@

            <table class="table">
                <thead>
                    <tr>
                        <th>@Html.DisplayNameFor(m => m.Currencies.FirstOrDefault().Symbol)</th>
                        <th>@Html.DisplayNameFor(m => m.Currencies.FirstOrDefault().Code)</th>
                        <th>@Html.DisplayNameFor(m => m.Currencies.FirstOrDefault().Name)</th>
                    </tr>
                </thead>
                <tbody>
            @foreach (var c in Model.Currencies)
            {
                   <tr>
                        <td class="coin">@Html.DisplayFor(m => c.Symbol)   </td>
                        <td> @Html.DisplayFor(m => c.Code) </td>
                        <td>@Html.DisplayFor(m => c.Name) </td>
                    </tr>                       
            }
 
                </tbody>
            </table>


        </dd>
    </dl>
</div>
<div>

    <a asp-action="Index">Back to List</a>
</div>

StockExchange/Views/Countries/Index.cshtml
@model IEnumerable<StockExchangeLib.Models.Country>

@{
    ViewData["Title"] = "Index";
}

<h1>Index</h1>



<div class="row">
    <div class="col-6">
        <input id="my-locate" type="text" />
        <button id="bt-locate" class="btn btn-primary">Buscar</button>
        <button id="bt-reset" class="btn btn-dark">Resetear</button>
        <button id="bt-another" class="btn btn-dark">Función anónima</button>
    </div>
</div>
<!--
    <div id="my-message" class="alert alert-warning">
    Introduce un texto válido, por favor
</div>
-->

<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Name)
            </th>
            <th colspan="2">
                @Html.DisplayNameFor(model => model.Currencies)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr class="@item.Name.ToLower()">
            <td>
                <span>
                    <a asp-controller="Countries" asp-action="Details" asp-route-id="@item.Id" >@Html.DisplayFor(modelItem => item.Name)</a> 
                </span>                
            </td>
            <td class="coin">
                @*@Html.DisplayFor(modelItem => item.CurrencyType)*@
                @foreach (var c in item.Currencies)
                {
                    @Html.DisplayFor(m => c.Symbol)                        
                }
               
            </td>
            <td>
                (@item.Currencies.Count)
            </td>
            <td>
            @*    <a asp-action="Edit" asp-route-id="@item.CountryId">Edit</a> |*@
                <a asp-action="Details" asp-route-id="@item.Id">Details</a> 
            </td>
        </tr>
}
    </tbody>
</table>

@section Scripts
{
<script>

    function searchCutre() {
        console.log("Buscando cutremente...");

        $("tr").hide();

        var text = $("#my-locate").val().toLowerCase().trim();

        console.log("el texto a buscar es: ", text);

        //if ( text=="" ) {
        if ( text==="" ) {
            $("#my-message").show();
        }
        else {
            $("#my-message").hide();

            $("." + text ).show();
        }
    }

    function searchMenosCutre() {

        var text = $("#my-locate").val().toLowerCase().trim();

        $("table tbody tr").each( function() {

            // Escribo el texto de cada elemento de la colección: de cada fila
            //console.log( $(this).text() );

            //console.log( $(this).text().toLowerCase().indexOf(text) );

            if ( $(this).text().toLowerCase().indexOf(text) > -1 ) {
                $(this).show();
            }
            else {
                $(this).hide();
            }

        } );
    }

    function resetCountries() {

        $("tr").show();
    }

    function initialize() {
        //alert("cargando");
        // Antes buscaba de forma cutre
        //$("#bt-locate").click(searchCutre);

        // Ahora buscamos mejor
        $("#bt-locate").click(searchMenosCutre);

        $("#bt-reset").click(resetCountries);

        $("#bt-another").click( function () {
            console.log("Esto es una función anónima");

            var unNumero = 8;

            if ( unNumero=="8") {
                console.log("Funciona con == comprar un entero y un string");
            }

            if ( unNumero==="8") {
                console.log("¿Funciona con === comprar un entero y un string?");
            }

            if ( unNumero === parseInt("8")) {
                console.log("Funciona con === comprar un entero y un string sólo cuándo coinciden los tipos");
            }
        } );
    }

    $().ready(initialize);
</script>
}

StockExchange/Views/Currencies/Details.cshtml
@model StockExchangeLib.Models.Currency

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>Currency</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Code)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Code)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Name)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Symbol)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Symbol)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model.Id">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

StockExchange/Views/Currencies/Index.cshtml
@model IEnumerable<StockExchangeLib.Models.Currency>

@{
    ViewData["Title"] = "Index";
}

<h1>Index</h1>

<div class="row">
    <div class="col-6">
        <input id="my-locate" type="text" />
    </div>
    <div class="col-6">
        <button id="bt-reset" class="btn btn-dark">Reset</button>
    </div>
</div>

<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Code)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Name)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Symbol)
            </th>
            <th>Total</th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Code)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Name)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Symbol)
            </td>
            <td>
                @item.Countries.Count
            </td>
            <td>        
                <a asp-action="Details" asp-route-id="@item.Id">Details</a> 
            </td>
        </tr>
}
    </tbody>
</table>

@section Scripts
{
    <script>

        function search() {

            var text = $("#my-locate").val().toLowerCase().trim();

            console.log("tecla pulsada detectada. Texto: ", text);

            $("table tbody tr").each( function () {

                if ( $(this).text().toLowerCase().indexOf(text) > -1 ) {
                    $(this).show();
                }
                else {
                    $(this).hide();
                }

            } );
        }

        function initialize() {
            
            $("#my-locate").keyup(search);

            $("#bt-reset").click( function () {

                $("tr").show();
            } );
        }

        $().ready(initialize);

        /*
        // O función anónima
        $().ready(function () {
            // código
        });
        */

    </script>
}

StockExchange/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

StockExchange/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - StockExchange</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">StockExchange</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-controller="Countries" asp-action="Index">Countries</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-controller="Currencies" asp-action="Index">Currencies</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - StockExchange - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>